# Generated by Django 4.1.1 on 2022-09-06 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('article', models.CharField(max_length=64)),
                ('slug', models.SlugField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='PropertyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value_type', models.CharField(choices=[('int', 'integer'), ('str', 'string')], max_length=3)),
                ('code_url', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_val', models.CharField(max_length=128)),
                ('digit_val', models.FloatField()),
                ('code_url', models.CharField(max_length=64)),
                ('product', models.ManyToManyField(to='catalog.product')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.propertyobject')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='props',
            field=models.ManyToManyField(to='catalog.propertyobject'),
        ),
    ]
