# Generated by Django 4.1.1 on 2022-09-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_props'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvalue',
            name='digit_val',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='str_val',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
