# Generated by Django 4.1.1 on 2022-09-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_propertyvalue_digit_val_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertyobject',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop_value', to='catalog.propertyobject'),
        ),
    ]
